defmodule PolyHok do
  @on_load :load_nifs

  defp load_nifs do
    load_info = :erlang.load_nif(String.to_charlist("./priv/gpu_nifs"), 0)

    case load_info do
      :ok ->
        :ok

      {:error, {reason, text}} ->
        raise("failed to load NIF library: #{inspect(reason)}: #{to_string(text)}")
    end
  end

  defmacro clo({:fn, aa, [{:->, bb, [para, body]}]}) do
    body = PolyHok.CudaBackend.add_return(body)
    funs = JIT.find_functions({:fn, aa, [{:->, bb, [para, body]}]})
    name = "anon_" <> PolyHok.CudaBackend.gen_lambda_name()

    free = JIT.find_free_vars({:fn, aa, [{:->, bb, [para, body]}]})

    extra =
      free
      |> Enum.map(fn p -> {p, [], nil} end)

    free = Enum.map(free, fn p -> String.to_atom(name <> Atom.to_string(p)) end)
    function = {:fn, aa, [{:->, bb, [para ++ extra, body]}]}

    resp =
      quote(
        do:
          {:closure, unquote(name),
           {unquote(Macro.escape(function)), unquote(Macro.escape(funs))}, unquote(free),
           unquote(extra)}
      )

    resp
  end

  defmacro phok({:fn, aa, [{:->, bb, [para, body]}]}) do
    body = PolyHok.CudaBackend.add_return(body)
    funs = JIT.find_functions({:fn, aa, [{:->, bb, [para, body]}]})
    name = "anon_" <> PolyHok.CudaBackend.gen_lambda_name()
    function = {:fn, aa, [{:->, bb, [para, body]}]}

    resp =
      quote(
        do: {:anon, unquote(name), {unquote(Macro.escape(function)), unquote(Macro.escape(funs))}}
      )

    resp
  end

  defmacro defmodule(header, do: body) do
    {:__aliases__, _, [module_name]} = header
    body = normalize_dsl_body(body)
    JIT.process_module(module_name, body)

    ast_new_module = PolyHok.CudaBackend.gen_new_module(header, body)
    ast_new_module
  end

  # Canonicalize DSL-only calls so downstream passes do not depend on caller imports.
  defp normalize_dsl_body({:__block__, meta, definitions}) do
    {:__block__, meta, Enum.map(definitions, &normalize_dsl_definition/1)}
  end

  defp normalize_dsl_body(definition), do: normalize_dsl_definition(definition)

  defp normalize_dsl_definition({:include, meta, args}) do
    {{:., meta, [{:__aliases__, meta, [:PolyHok]}, :include]}, meta, args}
  end

  defp normalize_dsl_definition(definition), do: definition

  defmacro include(inc_list) do
    includes =
      inc_list
      |> Enum.map(fn {_, _, [module]} -> to_string(module) end)

    file = File.open!("c_src/Elixir.App.cu", [:write])
    IO.write(file, "#include \"erl_nif.h\"\n\n")

    Enum.map(includes, fn module ->
      code =
        File.read!("c_src/Elixir.#{module}.cu")
        |> String.split("\n")
        |> Enum.drop(1)
        |> Enum.join("\n")

      IO.write(file, code)
    end)

    File.close(file)

    {result, errcode} =
      System.cmd(
        "nvcc",
        [
          "--shared",
          "--compiler-options",
          "'-fPIC'",
          "-o",
          "priv/Elixir.App.so",
          "c_src/Elixir.App.cu"
        ],
        stderr_to_stdout: true
      )

    if errcode == 1 || errcode == 2 do
      raise "Error when compiling .cu file generated by PolyHok:\n#{result}"
    end
  end

  ########   GNX stuff

  def get_type({:nx, type, _shape, _name, _ref}) do
    type
  end

  def get_shape_gnx({:nx, _type, shape, _name, _ref}) do
    shape
  end

  def get_shape({:nx, _type, shape, _name, _ref}) do
    shape
  end

  def new_gnx(%Nx.Tensor{data: data, type: type, shape: shape, names: name}) do
    %Nx.BinaryBackend{state: array} = data

    {l, c} =
      case shape do
        {c} -> {1, c}
        {l, c} -> {l, c}
        {l1, l2, c} -> {l1 * l2, c}
      end

    ref =
      case type do
        {:f, 32} -> create_gpu_array_nx_nif(array, l, c, Kernel.to_charlist("float"))
        {:f, 64} -> create_gpu_array_nx_nif(array, l, c, Kernel.to_charlist("double"))
        {:s, 32} -> create_gpu_array_nx_nif(array, l, c, Kernel.to_charlist("int"))
        x -> raise "new_gnx: type #{x} not suported"
      end

    {:nx, type, shape, name, ref}
  end

  # def random_gnx(low, high, n) do
  #   {:nx, {:f, 32}, {n}, [nil], create_gpu_array_random_nx_nif(low, high, n)}
  # end

  def random_gnx(low, high, n) do
    {:nx, {:f, 32}, {n}, [nil], create_gpu_array_random_nx_nif(low, high, n)}
  end

  def new_gnx(l, c, type) do
    ref =
      case type do
        {:f, 32} -> new_gpu_array_nif(l, c, Kernel.to_charlist("float"))
        {:f, 64} -> new_gpu_array_nif(l, c, Kernel.to_charlist("double"))
        {:s, 32} -> new_gpu_array_nif(l, c, Kernel.to_charlist("int"))
        x -> raise "new_gnx: type #{x} not suported"
      end

    {:nx, type, {l, c}, [nil, nil], ref}
  end

  def new_gnx({c}, type) do
    l = 1

    ref =
      case type do
        {:f, 32} -> new_gpu_array_nif(l, c, Kernel.to_charlist("float"))
        {:f, 64} -> new_gpu_array_nif(l, c, Kernel.to_charlist("double"))
        {:s, 32} -> new_gpu_array_nif(l, c, Kernel.to_charlist("int"))
        x -> raise "new_gnx: type #{x} not suported"
      end

    {:nx, type, {c}, [nil], ref}
  end

  def new_gnx({l, c}, type) do
    ref =
      case type do
        {:f, 32} -> new_gpu_array_nif(l, c, Kernel.to_charlist("float"))
        {:f, 64} -> new_gpu_array_nif(l, c, Kernel.to_charlist("double"))
        {:s, 32} -> new_gpu_array_nif(l, c, Kernel.to_charlist("int"))
        x -> raise "new_gnx: type #{x} not suported"
      end

    {:nx, type, {l, c}, [nil, nil], ref}
  end

  def new_gnx({d1, d2, d3}, type) do
    {l, c} = {d1 * d2, d3}

    ref =
      case type do
        {:f, 32} -> new_gpu_array_nif(l, c, Kernel.to_charlist("float"))
        {:f, 64} -> new_gpu_array_nif(l, c, Kernel.to_charlist("double"))
        {:s, 32} -> new_gpu_array_nif(l, c, Kernel.to_charlist("int"))
        x -> raise "new_gnx: type #{x} not suported"
      end

    {:nx, type, {d1, d2, d3}, [nil, nil, nil], ref}
  end

  def get_gnx({:matrex, ref, {rows, columns}}) do
    bin = get_gpu_array_nif(ref, rows, columns, Kernel.to_charlist("float"))
    array = <<rows::unsigned-integer-little-32, columns::unsigned-integer-little-32, bin::binary>>
    %Matrex{data: array}
  end

  def get_gnx({:nx, type, shape, name, ref}) do
    # IO.puts "aqui..."
    {l, c} =
      case shape do
        {c} -> {1, c}
        {l, c} -> {l, c}
        {d1, d2, d3} -> {d1 * d2, d3}
      end

    ref =
      case type do
        {:f, 32} -> get_gpu_array_nif(ref, l, c, Kernel.to_charlist("float"))
        {:f, 64} -> get_gpu_array_nif(ref, l, c, Kernel.to_charlist("double"))
        {:s, 32} -> get_gpu_array_nif(ref, l, c, Kernel.to_charlist("int"))
        x -> raise "new_gnx: type #{x} not suported"
      end

    %Nx.Tensor{data: %Nx.BinaryBackend{state: ref}, type: type, shape: shape, names: name}
  end

  def get_array_type(%Nx.Tensor{data: _data, type: _type, shape: _shape, names: _name} = nx) do
    Nx.type(nx)
  end

  def get_array_type(%Matrex{data: _matrix}) do
    {:f, 32}
  end

  def create_gpu_array_random_nx_nif(_low, _high, _n) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def new_gpu_array_nif(_l, _c, _type) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def get_gpu_array_nif(_matrex, _l, _c, _type) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def create_gpu_array_nx_nif(_matrex, _l, _c, _type) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def new_gpu_nx_nif(_l, _c, _type) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def get_nx_nif(_matrex, _l, _c, _type) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def create_nx_ref_nif(_matrex, _l, _c, _type) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def create_ref_nif(_matrex) do
    :erlang.nif_error(:nif_not_loaded)
  end

  ######  GMatrex stuff:

  def new_pinned_nif(_list, _length) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def new_gmatrex_pinned_nif(_array) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def new_ref_nif(_matrex) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def synchronize_nif() do
    :erlang.nif_error(:nif_not_loaded)
  end

  def synchronize() do
    synchronize_nif()
  end

  def get_matrex_nif(_ref, _rows, _cols) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def load_kernel_nif(_module, _fun) do
    :erlang.nif_error(:nif_not_loaded)
  end

  def load_fun_nif(_module, _fun) do
    :erlang.nif_error(:nif_not_loaded)
  end

  # I should verify where this code is being used, because it was not working properly before and that's might be a sight that it wans't being used.
  def load_ast(kernel_name) when is_atom(kernel_name) do
    send(:module_server, {:get_ast, kernel_name, self()})

    receive do
      {:ast, ast} ->
        ast

      h ->
        raise "unknown message for function type server #{inspect(h)}"
    end
  end

  ############################################################## Loading types and asts from files
  def load_ast(kernel) do
    {_module, f_name} =
      case Macro.escape(kernel) do
        {:&, [], [{:/, [], [{{:., [], [module, f_name]}, [no_parens: true], []}, _nargs]}]} ->
          {module, f_name}

        f ->
          {:ok, f}
      end

    send(:module_server, {:get_ast, f_name, self()})

    receive do
      {:ast, ast} -> ast
      h -> raise "unknown message for function type server #{inspect(h)}"
    end
  end

  def load_type(kernel) do
    case Macro.escape(kernel) do
      {:&, [], [{:/, [], [{{:., [], [module, kernelname]}, [no_parens: true], []}, _nargs]}]} ->
        bytes = File.read!("c_src/#{module}.types")
        map = :erlang.binary_to_term(bytes)

        resp = Map.get(map, String.to_atom("#{kernelname}"))
        resp

      _ ->
        raise "PolyHok.build: invalid kernel"
    end
  end

  def load(kernel) do
    case Macro.escape(kernel) do
      {:&, [], [{:/, [], [{{:., [], [_module, kernelname]}, [no_parens: true], []}, _nargs]}]} ->
        PolyHok.load_kernel_nif(to_charlist("Elixir.App"), to_charlist("#{kernelname}"))

      _ ->
        raise "PolyHok.build: invalid kernel"
    end
  end

  def load_fun(fun) do
    case Macro.escape(fun) do
      {:&, [], [{:/, [], [{{:., [], [_module, funname]}, [no_parens: true], []}, _nargs]}]} ->
        PolyHok.load_fun_nif(to_charlist("Elixir.App"), to_charlist("#{funname}"))

      _ ->
        raise "PolyHok.invalid function"
    end
  end

  def load_lambda(lambda) do
    PolyHok.load_fun_nif(to_charlist("Elixir.App"), to_charlist(lambda))
  end

  # Prepares the  arguments before making the real kernell call
  defp process_args([{:anon, name, _type} | t1]) do
    [load_lambda(name) | process_args(t1)]
  end

  defp process_args([{:func, func, _type} | t1]) do
    [load_fun(func) | process_args(t1)]
  end

  defp process_args([{:nx, _type, _shape, _name, ref} | t1]) do
    [ref | process_args(t1)]
  end

  defp process_args([{matrex, {_rows, _cols}} | t1]) do
    [matrex | process_args(t1)]
  end

  defp process_args([arg | t1]) when is_function(arg) do
    [load_fun(arg) | process_args(t1)]
  end

  defp process_args([arg | t1]) do
    [arg | process_args(t1)]
  end

  defp process_args([]), do: []

  #########################
  defp process_args_no_fun([{:anon, _name, _type} | t1]) do
    process_args_no_fun(t1)
  end

  defp process_args_no_fun([{:func, _func, _type} | t1]) do
    process_args_no_fun(t1)
  end

  defp process_args_no_fun([{:nx, _type, _shape, _name, ref} | t1]) do
    [ref | process_args_no_fun(t1)]
  end

  defp process_args_no_fun([{matrex, {_rows, _cols}} | t1]) do
    [matrex | process_args_no_fun(t1)]
  end

  defp process_args_no_fun([arg | t1]) when is_function(arg) do
    process_args_no_fun(t1)
  end

  defp process_args_no_fun([arg | t1]) do
    [arg | process_args_no_fun(t1)]
  end

  defp process_args_no_fun([]), do: []

  ############################ Type checking the arguments at runtime

  ### first two arguments are used for error messages. Takes a list of types and a list of actual parameters and type checks them

  def type_check_args(kernel, narg, [:matrex | t1], [a | t2]) do
    case a do
      {_ref, {_l, _c}} -> type_check_args(kernel, narg + 1, t1, t2)
      {:nx, _type, _shape, _name, _ref} -> type_check_args(kernel, narg + 1, t1, t2)
      _ -> raise "#{kernel}: argument #{narg} should have type gmatrex."
    end
  end

  def type_check_args(kernel, narg, [:float | t1], [v | t2]) do
    if is_float(v) do
      type_check_args(kernel, narg + 1, t1, t2)
    else
      raise "#{kernel}: argument #{narg} should have type float."
    end
  end

  def type_check_args(kernel, narg, [:int | t1], [v | t2]) do
    if is_integer(v) do
      type_check_args(kernel, narg + 1, t1, t2)
    else
      raise "#{kernel}: argument #{narg} should have type int."
    end
  end

  def type_check_args(kernel, narg, [{rt, ft} | t1], [{:func, func, {art, aft}} | t2]) do
    f_name =
      case Macro.escape(func) do
        {:&, [], [{:/, [], [{{:., [], [_module, f_name]}, [no_parens: true], []}, _nargs]}]} ->
          f_name

        _ ->
          raise "Argument to spawn should be a function."
      end

    if rt == art do
      type_check_function(f_name, 0, ft, aft)
      type_check_args(kernel, narg + 1, t1, t2)
    else
      raise "#{kernel}: #{f_name} function has return type #{art}, was excpected to have type #{rt}."
    end
  end

  def type_check_args(kernel, narg, [{rt, ft} | t1], [{:anon, _name, {art, aft}} | t2]) do
    if rt == art do
      type_check_function("anonymous", 1, ft, aft)
      type_check_args(kernel, narg + 1, t1, t2)
    else
      raise "#{kernel}: anonymous function has return type #{art}, was excpected to have type #{rt}."
    end
  end

  def type_check_args(kernel, narg, [{rt, ft} | t1], [func | t2]) when is_function(func) do
    {art, aft} = load_type(func)

    f_name =
      case Macro.escape(func) do
        {:&, [], [{:/, [], [{{:., [], [_module, f_name]}, [no_parens: true], []}, _nargs]}]} ->
          f_name

        _ ->
          raise "Argument to spawn should be a function."
      end

    if rt == art do
      type_check_function(f_name, 0, ft, aft)
      type_check_args(kernel, narg + 1, t1, t2)
    else
      raise "#{kernel}: #{f_name} function has return type #{art}, was excpected to have type #{rt}."
    end
  end

  def type_check_args(_k, _narg, [], []), do: []

  def type_check_args(k, _narg, a, v),
    do: raise("Wrong number of arguments when calling #{k}. #{inspect(a)} #{inspect(v)} ")

  def type_check_function(k, narg, [at | t1], [ft | t2]) do
    if at == ft do
      type_check_function(k, narg + 1, t1, t2)
    else
      raise "#{k}: argument #{narg} has type #{ft} and should have type #{at}"
    end
  end

  def type_check_function(_k, _narg, [], []), do: []

  def type_check_function(k, _narg, a, v),
    do: raise("Wrong number of arguments when calling #{k}. #{inspect(a)} #{inspect(v)} ")

  ###########  Spawn with jit compilation, at compilation we build a representation for the kernel: {:ker, its type, its ast} and leave a call to spawn

  def spawn(k, t, b, l) do
    kernel_name = JIT.get_kernel_name(k)

    {kast, fun_graph} =
      case load_ast(k) do
        {a, g} -> {a, g}
        nil -> raise "Unknown kernel #{inspect(kernel_name)}"
      end

    # IO.inspect(kast, label: "Kast = ")
    {kast, l} = JIT.closure_elimination(kast, l)

    delta = JIT.gen_types_delta(kast, l)
    inf_types = JIT.infer_types(kast, delta)
    subs = JIT.get_function_parameters(kast, l)
    kernel = JIT.compile_kernel(kast, inf_types, subs)
    funs = JIT.get_function_parameters_and_their_types(kast, l, inf_types)

    other_funs =
      fun_graph
      |> Enum.map(fn x -> {x, inf_types[x]} end)
      |> Enum.filter(fn {_, i} -> i != nil end)

    comp = Enum.map(funs ++ other_funs, &JIT.compile_function/1)
    comp = Enum.reduce(comp, [], fn x, y -> y ++ x end)
    includes = JIT.get_includes()
    prog = [includes | comp] ++ [kernel]

    prog = Enum.reduce(prog, "", fn x, y -> y <> x end)

    # maybe_dump_jit_cuda_source(kernel_name, prog) # uncomment this if needed to check cuda sources

    args = process_args_no_fun(l)
    types_args = JIT.get_types_para(kast, inf_types)

    # IO.inspect(kernel_name, label: "Kernel name: ")
    # IO.inspect(prog, label: "prog content: ")

    jit_compile_and_launch_nif(
      Kernel.to_charlist(kernel_name),
      Kernel.to_charlist(prog),
      t,
      b,
      length(args),
      types_args,
      args
    )
  end

  def spawn_nif(_k, _t, _b, _l), do: :erlang.nif_error(:nif_not_loaded) 

  def jit_compile_and_launch_nif(_n, _k, _t, _b, _size, _types, _l) do
    :erlang.nif_error(:nif_not_loaded)
  end

  # defp maybe_dump_jit_cuda_source(kernel_name, prog) do
  #   case System.get_env("POLYHOK_DUMP_CUDA_DIR") do
  #     nil ->
  #       :ok
  #
  #     "" ->
  #       :ok
  #
  #     dump_dir ->
  #       File.mkdir_p!(dump_dir)
  #
  #       timestamp = System.os_time(:microsecond)
  #       filename = "#{kernel_name}_#{timestamp}.cu"
  #       path = Path.join(dump_dir, filename)
  #       File.write!(path, prog)
  #       IO.puts("PolyHok JIT CUDA dumped to: #{path}")
  #   end
  # end

  def new_nx_from_function(l, c, type, fun) do
    size = l * c

    ref =
      case type do
        {:f, 32} -> new_matrix_from_function_f(size - 1, fun, <<fun.()::float-little-32>>)
        {:f, 64} -> new_matrix_from_function_d(size - 1, fun, <<fun.()::float-little-64>>)
        {:s, 32} -> new_matrix_from_function_i(size - 1, fun, <<fun.()::integer-little-32>>)
      end

    %Nx.Tensor{data: %Nx.BinaryBackend{state: ref}, type: type, shape: {l, c}, names: [nil, nil]}
  end

  #######################
  defp new_matrix_from_function_d(0, _, accumulator), do: accumulator

  defp new_matrix_from_function_d(size, function, accumulator),
    do:
      new_matrix_from_function_d(
        size - 1,
        function,
        <<accumulator::binary, function.()::float-little-64>>
      )

  defp new_matrix_from_function_i(0, _, accumulator), do: accumulator

  defp new_matrix_from_function_i(size, function, accumulator),
    do:
      new_matrix_from_function_i(
        size - 1,
        function,
        <<accumulator::binary, function.()::integer-little-32>>
      )

  defp new_matrix_from_function_f(0, _, accumulator), do: accumulator

  defp new_matrix_from_function_f(size, function, accumulator),
    do:
      new_matrix_from_function_f(
        size - 1,
        function,
        <<accumulator::binary, function.()::float-little-32>>
      )

  ##############################
  def new_nx_from_function_arg(l, c, type, fun) do
    size = l * c

    ref =
      case type do
        {:f, 32} ->
          new_matrix_from_function_f_arg(size - 1, fun, <<fun.(size)::float-little-32>>)

        {:f, 64} ->
          new_matrix_from_function_d_arg(size - 1, fun, <<fun.(size)::float-little-64>>)

        {:s, 32} ->
          new_matrix_from_function_i_arg(size - 1, fun, <<fun.(size)::integer-little-32>>)
      end

    %Nx.Tensor{data: %Nx.BinaryBackend{state: ref}, type: type, shape: {l, c}, names: [nil, nil]}
  end

  #######################
  defp new_matrix_from_function_d_arg(0, _, accumulator), do: accumulator

  defp new_matrix_from_function_d_arg(size, function, accumulator),
    do:
      new_matrix_from_function_d_arg(
        size - 1,
        function,
        <<accumulator::binary, function.(size)::float-little-64>>
      )

  defp new_matrix_from_function_i_arg(0, _, accumulator), do: accumulator

  defp new_matrix_from_function_i_arg(size, function, accumulator),
    do:
      new_matrix_from_function_i_arg(
        size - 1,
        function,
        <<accumulator::binary, function.(size)::integer-little-32>>
      )

  defp new_matrix_from_function_f_arg(0, _, accumulator), do: accumulator

  defp new_matrix_from_function_f_arg(size, function, accumulator),
    do:
      new_matrix_from_function_f_arg(
        size - 1,
        function,
        <<accumulator::binary, function.(size)::float-little-32>>
      )
end
